name: ğŸ•¹ï¸ Release Trigger

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    uses: ./.github/workflows/release-check.yml

  prepare:
    name: ğŸ”– Create Release PR
    needs: check
    if: ${{ needs.check.outputs.version_exists == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Git User
        uses: fregante/setup-git-user@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Update Metadata for Release
        run: uv run update --versions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release/${{ needs.check.outputs.release_tag }}
          title: |
            ğŸ› ï¸ chore: release ${{ needs.check.outputs.release_name }}
          commit-message: |
            ğŸ› ï¸ chore: release ${{ needs.check.outputs.release_name }}
          delete-branch: true
          sign-commits: true
